version: "2.2"
services:
  jobmanager:
    # image: pyflink:1.16.0
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/pyflink
    ports:
      - "8085:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
  taskmanager:
    # image: pyflink:1.16.0
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2

  pulsar:
    image: apachepulsar/pulsar:2.9.2
    container_name: pulsar
    ports:
      - "8080:8080"
      - "6650:6650"
    environment:
      PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
      systemTopicEnabled: "true"
      topicLevelPoliciesEnabled: "true"
      transactionCoordinatorEnabled: "true"
    command: >
      /bin/bash -c
      " bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone"

  pulsar-topics-setup:
    image: alpine
    container_name: pulsar-topics-setup
    build:
      context: .
      dockerfile: Dockerfile.pulsar-setup
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    # stdin_open: true # docker run -i
    # tty: true # docker run -t
    #
    depends_on:
      - pulsar
    command: >
      sh -c "
      docker exec pulsar bin/pulsar-admin topics create-partitioned-topic -p 1 persistent://public/default/my-topic && \
      docker exec pulsar bin/pulsar-admin topics set-retention -s -1 -t -1 persistent://public/default/my-topic && \
      docker exec pulsar bin/pulsar-admin topics create-partitioned-topic -p 1 persistent://public/default/results && \
      docker exec pulsar bin/pulsar-admin topics set-retention -s -1 -t -1 persistent://public/default/results
      "
